#!/bin/bash

put () {

    if [ -d _originals ]
    then
        echo '_originals already exists. Delete it first, if you do not need it.'
        exit
    else
        mkdir _originals
    fi

    DOTFILES="$(cd `dirname $0` && pwd)"

    dln tmux.conf

    dln mail/offlineimap.conf ~/.offlineimaprc
    dln mutt/muttrc ~/.muttrc

    dln fabricrc
    dln toprc

    dln git/config ~/.gitconfig
    dln git/ignore ~/.gitignore

    dln hg/hgrc ~/.hgrc
    dln hg/hgignore ~/.hgignore

    dln shell/zsh ~/.zshrc
    dln shell/env ~/.zshenv

    dln shell/bash ~/.bashrc

    echo Finished setting up links

    # TODO: Create a better way to manage these sub repos

    if [ -d hg/hg-prompt ]
    then
        rm -Rf hg/hg-prompt
    fi
    hg clone http://bitbucket.org/sjl/hg-prompt hg/hg-prompt

    if [ -d hg/hgshelve ]
    then
        rm -Rf hg/hgshelve
    fi
    hg clone https://sharat87@bitbucket.org/tksoh/hgshelve hg/hgshelve

    if [ -d mutt/solarized-colors ]
    then
        rm -Rf mutt/solarized-colors
    fi
    git clone git://github.com/altercation/mutt-colors-solarized.git mutt/solarized-colors

    if [ -d mail/offlineimap ]
    then
        rm -Rf mail/offlineimap
    fi
    git clone git://github.com/nicolas33/offlineimap.git mail/offlineimap

}

unput () {

    if [ ! -d _originals ]
    then
        echo '_originals directory does not exist. Nothing to restore.'
    fi

    for f in `ls -A _originals`
    do
        echo "> $f"
        mv "_originals/$f" ~/"$f"
    done

    echo 'Restored'

    rmdir _originals
    echo 'Removed _originals directory.'
}

reget () {

    # A few awesome tools
    (cd bin
        wget --no-check-certificate -O ack http://betterthangrep.com/ack-standalone
        wget --no-check-certificate -O droopy http://stackp.online.fr/wp-content/uploads/droopy
        wget --no-check-certificate -O lein https://github.com/technomancy/leiningen/raw/stable/bin/lein
        wget --no-check-certificate -O cake http://releases.clojure-cake.org/cake
    )

    # Stuff that make command line more fun!
    (cd shell/custom-configs
        wget --no-check-certificate -O sjl-z.sh https://github.com/sjl/z-zsh/raw/master/z.sh
        wget --no-check-certificate -O zsh-syntax-highlighting.zsh https://github.com/nicoulaj/zsh-syntax-highlighting/raw/master/zsh-syntax-highlighting.zsh
    )

    # Update my mercurial plugins
    (cd hg/hg-prompt/ && hg fetch)
    (cd hg/hgshelve/ && hg fetch)

    # Misc. updates
    (cd mutt/solarized-colors && git pull)
    (cd mail/offlineimap && git pull)

    # Download oh-my-zsh and set it up
    if [ -d "shell/oh-my-zsh" ]
    then
        (cd shell/oh-my-zsh && git pull)
    else
        git clone git@github.com:sharat87/oh-my-zsh.git shell/oh-my-zsh
    fi
    (cd shell/oh-my-zsh
        rm -Rfv custom
        ln -sv ../custom-configs custom
    )

}

main () {
    cmd="$1"
    if [ "$cmd" = "" ]
    then
        echo 'No command given'
        exit
    fi
    if [ "$cmd" == "put" ]
    then
        put "$@"
    elif [ "$cmd" == "unput" ]
    then
        unput "$@"
    elif [ "$cmd" == "reget" ]
    then
        reget "$@"
    else
        echo "Unknown command $cmd"
        exit
    fi
}

dln () {
    source="$1"
    target="$2"
    if [ "$target" = "" ]
    then
        target="$HOME/.$source"
    fi
    if isnode "$target"
    then
        mv "$target" _originals
    fi
    ln -s "$DOTFILES/$source" "$target"
}

# Check if a file exists
isnode () {
    [ -e "$1" -o -L "$1" ]
}

main "$@"
