#!/bin/bash
(

_rnum=$RANDOM
jdirname=/tmp/jarify/$_rnum
mkdir -vp $jdirname
cd $jdirname

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS=/home/sharat/calypso/software/release/build/com/calypso/apps/startup/AppStarter.class

for fname in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
    cp -v "$fname" .
done

export CLASSPATH=".:/home/sharat/labs/java/revise"

ls | while read fname
do
    if [ "${fname##*.}" = "class" ]
    then
        java PackageTest ${fname%%.class} 2>&1 | \
            awk '/^Exception in thread / { print substr($NF, 1, length($NF)-1) ".class" }'
    elif [ "${fname##*.}" = "java" ]
    then
        awk -v fname="$fname" '/^package / { gsub(/\./, "/"); print substr($NF, 1, length($NF)-1) "/" fname; exit }' "$fname"
    fi
done | while read pclass
do
    echo $pclass
    path=$(dirname $pclass)
    class=$(basename $pclass)
    if [ ! -d "$path" ]
    then
        mkdir -vp $path
    fi
    mv -v $class $path
done

cd ..
jarfile=$(zenity --file-selection --save --title "Enter jar file name" --filename "$_rnum.jar" --file-filter=\*.jar\|\*)
if [ ! -z "$jarfile" ]
then
    if [ -e "$jarfile" ]
    then
        jar -uf "$jarfile" -C $_rnum .
    else
        jar -cf "$jarfile" -C $_rnum .
    fi
    # xclip -in -selection c "$jarfile"
    # echo -n "$jarfile" | xsel --clipboard --input
fi

rm -Rf $jdirname

) &> /home/sharat/dotfiles/nautilus-scripts/bjar.log
