#!/bin/bash

while IFS= read -r line
do
    if [[ "$line" == Date:* ]]
    then
        echo -n "Date: "
        date -d "${line#Date: }" "+%a %b %e %l:%M %p %Z %Y"
    else
        echo "$line"
    fi
done
