#!/usr/bin/env python

import subprocess as sp
import os

def new_mail_count(maildir):
    return len(os.listdir(os.path.join(os.path.expanduser('~/Mail/Calypso'), maildir, 'new')))

maildirs = 'INBOX'.split()

total_new_mail_count = sum(map(new_mail_count, maildirs))

if total_new_mail_count != 0:
    sp.call('notify-send "{count} New mail(s)"'.format(count=total_new_mail_count), shell=True)
