# Symlink to this file from ~/.zshrc
# You should also symlink ~/.zshenv to zsh/env in this directory

parent="$(cd `dirname $0` && pwd)"
parent=~/dotfiles

if [ -e ~/.aliases ]
then
    source ~/.aliases
fi

source $parent/zsh/config
source $parent/zsh/utils
